import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration to control ordering
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "FAQ",
      items: [
        "FAQ/index",
        "FAQ/borrowing-liquidations",
        "FAQ/redemptions-and-delegations",
        "FAQ/usdu-and-earn",
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Tutorial - Basics',
    //   items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial - Extras',
    //   items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    // },
  ],
};

export default sidebars;
