import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar configuration to control ordering
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "doc",
      id: "FAQ/index",
      label: "The Uncap protocol",
    },
    {
      type: "doc",
      id: "FAQ/borrowing-liquidations",
      label: "Borrowing & Liquidations",
    },
    {
      type: "doc",
      id: "FAQ/redemptions-and-delegations",
      label: "Redemptions & Delegations",
    },
    {
      type: "doc",
      id: "FAQ/usdu-and-earn",
      label: "USDU & Earn",
    },
    // {
    //   type: 'category',
    //   label: 'Tutorial - Basics',
    //   items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial - Extras',
    //   items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    // },
  ],
};

export default sidebars;
